### ISSUE TITLE
Make all indicator files lower case

### ISSUE THREAD

**Issue by kuanb** [datakind/ccep-new-year#4]
Hey @mdgis 

Just a heads up that there is a risk for side effects on some browsers if we use rely on capitalization for the indicator files. They are already camel case (separated by underscores) so that should be all that is used to split the words. The text should all be lower case, both on the file names themselves and their string variables (from the lookup csv).

![image](https://user-images.githubusercontent.com/6053396/34907674-1095dd90-f837-11e7-8dde-c33e8e8dc4d3.png)

**Comment by kuanb** [comment]
@mdgis heads up this is not complete yet:

if you look on the gh-pages site, you'll notice this is causing errors with:

https://github.com/datakind/ccep-new-year/tree/master/data/indicator_files

All the indicator files, some files inside of 'data/', too, such as:
- ACS_Tracts_Final_Interpolated_06067.csv

**Comment by mdgis** [comment]
Not sure which commit since it was on the branch
